### ISSUE TITLE
训练语料

### ISSUE THREAD

**Issue by BruceHan98** [WENGSYX/Chinese-Word2vec-Medicine#1]
非常感谢你的工作，我想训练不同参数的词向量模型，请问能否提供训练所用的医学语料呢？

**Comment by WENGSYX** [comment]
好的，请留下您的邮箱地址

**Comment by BruceHan98** [comment]
***@***.***

非常感谢！


在 2021年9月20日，下午8:35，WENGSYX ***@***.***> 写道：

﻿

好的，请留下您的邮箱地址

**Comment by BruceHan98** [comment]
请发送到 brucehan1998@outlook.com ，十分感谢！
