### ISSUE TITLE
医学词向量模型可以公开吗？

### ISSUE THREAD

**Issue by gggdroa** [WENGSYX/Chinese-Word2vec-Medicine#10]
我看验证码为8888的是语料库  可以公开词向量模型吗

**Comment by WENGSYX** [comment]
你好，这个确实是词向量模型，可以直接下载使用。
model = KeyedVectors.load_word2vec_format('Medical.txt', binary=False)

**Comment by gggdroa** [comment]
> 你好，这个确实是词向量模型，可以直接下载使用。 model = KeyedVectors.load_word2vec_format('Medical.txt', binary=False)

好的谢谢  已看到
