### ISSUE TITLE
训练词向量，most_similar()结果不好，是哪里有问题吗？

### ISSUE THREAD

**Issue by Josoope** [WENGSYX/Chinese-Word2vec-Medicine#11]
import multiprocessing
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence

inp='./dict/med_word.txt'##你已经处理好的语料
outp1='./jieba/data_model/word2vecmodel'##world2的模型
outp2='./jieba/data_vector/word2vector'##词向量化后的数据
model=Word2Vec(LineSentence(inp),epochs=10,sg=0,vector_size=50,window=3,min_count=1,workers=multiprocessing.cpu_count())
model.save(outp1)
model.wv.save_word2vec_format(outp2,binary=False)

sim = model.wv.most_similar('海马', topn = 10)
print(sim)
输出的结果是：
[('前置胎盘', 0.5016711950302124), ('感染性腹泻', 0.4655754864215851), ('滴虫性阴道炎', 0.45234766602516174), ('蛋白质粉', 0.4456830322742462), ('盆浴', 0.4385753870010376), ('防风通圣丸', 0.4252159595489502), ('慢性直肠炎', 0.42219510674476624), ('射血分数', 0.4189762473106384), ('阴茎延长术', 0.4165302813053131), ('电离辐射', 0.40409475564956665)]

和作者的结果不太一样，求指教

**Comment by WENGSYX** [comment]
本项目中的med_word.txt只是生物医学高频词表，而不是训练语料。训练语料超过1G，可以从此处查找https://github.com/WENGSYX/CMCQA

首先对训练语料预处理，比如使用jieba：将高频词表中的词汇添加到jieba中，然后使用jieba对训练语料切词。
然后按照你的训练代码进行训练词向量。

**Comment by Josoope** [comment]
好的，谢谢
